# Find LIBLZMA
# LIBLZMA_FOUND - system has the LIBLZMA library
# LIBLZMA_INCLUDE_DIR - the LIBLZMA include directory
# LIBLZMA_LIBRARIES - The libraries needed to use LIBLZMA

if (LIBLZMA_INCLUDE_DIR AND LIBLZMA_LIBRARIES)
	# in cache already
	SET(LIBLZMA_FOUND TRUE)
else (LIBLZMA_INCLUDE_DIR AND LIBLZMA_LIBRARIES)
	FIND_PATH(LIBLZMA_INCLUDE_DIR lzma.h
		 ${LIBLZMA_ROOT}/include/
		 /usr/include/
		 /usr/local/include/
	)

	FIND_LIBRARY(LIBLZMA_LIBRARIES NAMES lzma
		PATHS
		${LIBLZMA_ROOT}/lib
		${LIBLZMA_ROOT}/lib64
		/usr/lib
		/usr/lib64
		/usr/local/lib
		/usr/local/lib64
		)

	if (LIBLZMA_INCLUDE_DIR AND LIBLZMA_LIBRARIES)
		 set(LIBLZMA_FOUND TRUE)
	endif (LIBLZMA_INCLUDE_DIR AND LIBLZMA_LIBRARIES)

	if (LIBLZMA_FOUND)
		 if (NOT LIBLZMA_FIND_QUIETLY)
				message(STATUS "Found LIBLZMA: ${LIBLZMA_LIBRARIES}")
		 endif (NOT LIBLZMA_FIND_QUIETLY)
	else (LIBLZMA_FOUND)
		 if (LIBLZMA_FIND_REQUIRED)
				message(FATAL_ERROR "Could NOT find LIBLZMA")
		 endif (LIBLZMA_FIND_REQUIRED)
	endif (LIBLZMA_FOUND)

	MARK_AS_ADVANCED(LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARIES)
endif (LIBLZMA_INCLUDE_DIR AND LIBLZMA_LIBRARIES)

